version: '3'
services:
  linqbot:
    image: linqbin/linqbot:latest
    env_file:
      - .env
    container_name: linqbot
    volumes:
      - ~/.linqbot:/app/db
    command: 'sh ./migrate-and-start.sh'
